<a href="https://colab.research.google.com/github/sledhead/simple_python/blob/main/img_reviewer_yolov8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
%pip install ultralytics
import ultralytics
ultralytics.checks()

Ultralytics YOLOv8.2.32 🚀 Python-3.10.12 torch-2.3.0+cu121 CUDA:0 (Tesla T4, 15102MiB)
Setup complete ✅ (2 CPUs, 12.7 GB RAM, 30.2/78.2 GB disk)


In [2]:
from ultralytics import YOLO

model = YOLO('yolov8n.pt')



100%|██████████| 6.23M/6.23M [00:00<00:00, 120MB/s]


In [23]:
results = model("test9.jpg")

print(results[0].boxes)



image 1/1 /content/test9.jpg: 384x640 1 cow, 9.6ms
Speed: 3.4ms preprocess, 9.6ms inference, 1.7ms postprocess per image at shape (1, 3, 384, 640)
ultralytics.engine.results.Boxes object with attributes:

cls: tensor([19.], device='cuda:0')
conf: tensor([0.8165], device='cuda:0')
data: tensor([[2.2344e+03, 1.1444e+02, 2.5061e+03, 3.2839e+02, 8.1654e-01, 1.9000e+01]], device='cuda:0')
id: None
is_track: False
orig_shape: (1728, 3072)
shape: torch.Size([1, 6])
xywh: tensor([[2370.2300,  221.4182,  271.7415,  213.9478]], device='cuda:0')
xywhn: tensor([[0.7716, 0.1281, 0.0885, 0.1238]], device='cuda:0')
xyxy: tensor([[2234.3594,  114.4443, 2506.1008,  328.3921]], device='cuda:0')
xyxyn: tensor([[0.7273, 0.0662, 0.8158, 0.1900]], device='cuda:0')


In [14]:
#print(results)
print(type(results[0]))
print(dir(results[0]))
print(type(results[0].boxes))

<class 'ultralytics.engine.results.Results'>
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__len__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_apply', '_keys', 'boxes', 'cpu', 'cuda', 'keypoints', 'masks', 'names', 'new', 'numpy', 'obb', 'orig_img', 'orig_shape', 'path', 'plot', 'probs', 'save', 'save_crop', 'save_dir', 'save_txt', 'show', 'speed', 'summary', 'to', 'tojson', 'update', 'verbose']
<class 'ultralytics.engine.results.Boxes'>


In [15]:
print(results[0].probs)

None


In [16]:
print(results[0].boxes)

ultralytics.engine.results.Boxes object with attributes:

cls: tensor([2., 0.], device='cuda:0')
conf: tensor([0.8811, 0.8479], device='cuda:0')
data: tensor([[2.1156e+03, 6.3506e+01, 3.0714e+03, 1.2583e+03, 8.8107e-01, 2.0000e+00],
        [1.7202e+03, 9.3403e+02, 2.1837e+03, 1.7189e+03, 8.4788e-01, 0.0000e+00]], device='cuda:0')
id: None
is_track: False
orig_shape: (1728, 3072)
shape: torch.Size([2, 6])
xywh: tensor([[2593.5256,  660.8830,  955.8335, 1194.7543],
        [1951.9688, 1326.4744,  463.5380,  784.8861]], device='cuda:0')
xywhn: tensor([[0.8442, 0.3825, 0.3111, 0.6914],
        [0.6354, 0.7676, 0.1509, 0.4542]], device='cuda:0')
xyxy: tensor([[2115.6089,   63.5058, 3071.4424, 1258.2601],
        [1720.1998,  934.0314, 2183.7378, 1718.9175]], device='cuda:0')
xyxyn: tensor([[0.6887, 0.0368, 0.9998, 0.7282],
        [0.5600, 0.5405, 0.7109, 0.9947]], device='cuda:0')


In [24]:
print(results[0].boxes.xyxy)
print(results[0].boxes.conf)
print(results[0].boxes.cls)

tensor([[2234.3594,  114.4443, 2506.1008,  328.3921]], device='cuda:0')
tensor([0.8165], device='cuda:0')
tensor([19.], device='cuda:0')


In [25]:
class_names = model.names
print(class_names)
icnt = 0
for each_class_name in results[0].boxes.cls:
  print(f'This object was found in the image: {class_names[int(each_class_name)]}  Here is the conf: {results[0].boxes.conf[icnt]} ')
  icnt = icnt + 1

{0: 'person', 1: 'bicycle', 2: 'car', 3: 'motorcycle', 4: 'airplane', 5: 'bus', 6: 'train', 7: 'truck', 8: 'boat', 9: 'traffic light', 10: 'fire hydrant', 11: 'stop sign', 12: 'parking meter', 13: 'bench', 14: 'bird', 15: 'cat', 16: 'dog', 17: 'horse', 18: 'sheep', 19: 'cow', 20: 'elephant', 21: 'bear', 22: 'zebra', 23: 'giraffe', 24: 'backpack', 25: 'umbrella', 26: 'handbag', 27: 'tie', 28: 'suitcase', 29: 'frisbee', 30: 'skis', 31: 'snowboard', 32: 'sports ball', 33: 'kite', 34: 'baseball bat', 35: 'baseball glove', 36: 'skateboard', 37: 'surfboard', 38: 'tennis racket', 39: 'bottle', 40: 'wine glass', 41: 'cup', 42: 'fork', 43: 'knife', 44: 'spoon', 45: 'bowl', 46: 'banana', 47: 'apple', 48: 'sandwich', 49: 'orange', 50: 'broccoli', 51: 'carrot', 52: 'hot dog', 53: 'pizza', 54: 'donut', 55: 'cake', 56: 'chair', 57: 'couch', 58: 'potted plant', 59: 'bed', 60: 'dining table', 61: 'toilet', 62: 'tv', 63: 'laptop', 64: 'mouse', 65: 'remote', 66: 'keyboard', 67: 'cell phone', 68: 'microw

In [9]:
import pandas as pd
import requests
#Will display upload box to user to allow a file to upload and encrypted.
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:

import os
base_folder_path = '/content/drive/MyDrive/Encryption_test/test_pics/test_imgs'

#Get list of files at this location
file_lst = os.listdir(base_folder_path)

print(f'The number of files in this folder: {len(file_lst)}')

#list of dict objects for files found with objects of value.
valueful_files_lst = []

for single_num in range(1,12,1):
  full_file_path = os.path.join(base_folder_path,file_lst[single_num])
  print(f'The file name: {file_lst[single_num]}')
  print(f'Full file path: {full_file_path}')
  print('.........................................')


for single_file_name in file_lst:
  full_file_path = os.path.join(base_folder_path,single_file_name)

  if(os.path.isfile(full_file_path) ):
    #confirm that this is file and not a directory

    results = model(full_file_path)

    icnt = 0
    bValidObjFound = False
    dict_found_file_objects = {}
    dict_found_file_objects['file_name'] = full_file_path
    for each_class_name in results[0].boxes.cls:
      print(f'This object was found in the image: {class_names[int(each_class_name)]}  Here is the conf: {results[0].boxes.conf[icnt]} ')


      if( results[0].boxes.conf[icnt] > 0.5 ):
        bValidObjFound = True

      obj_nm = 'obj_' + str(icnt)
      dict_found_file_objects[obj_nm] = class_names[int(each_class_name)]

      icnt = icnt + 1

    #was an object found that was greater than 50 % keep track of this file...
    if( bValidObjFound == True ):
      valueful_files_lst.append(dict_found_file_objects)







In [ ]:
print(f'the number of files recorded with useful objects found: {len(valueful_files_lst)}')

for single_recorded_file in valueful_files_lst:
  print('.....................................')
  print(single_recorded_file)
  print('.....................................')