<a href="https://colab.research.google.com/github/sledhead/simple_python/blob/main/img_reviewer_yolov8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
%pip install ultralytics
import ultralytics
ultralytics.checks()

Ultralytics YOLOv8.2.28 🚀 Python-3.10.12 torch-2.3.0+cu121 CUDA:0 (Tesla T4, 15102MiB)
Setup complete ✅ (2 CPUs, 12.7 GB RAM, 30.0/78.2 GB disk)


In [2]:
from ultralytics import YOLO

model = YOLO('yolov8n.pt')



100%|██████████| 6.23M/6.23M [00:00<00:00, 96.2MB/s]


In [3]:
results = model("test4.jpg")

print(results[0].boxes)



image 1/1 /content/test4.jpg: 384x640 2 persons, 1 truck, 81.0ms
Speed: 11.6ms preprocess, 81.0ms inference, 781.9ms postprocess per image at shape (1, 3, 384, 640)
ultralytics.engine.results.Boxes object with attributes:

cls: tensor([0., 0., 7.], device='cuda:0')
conf: tensor([0.8521, 0.7806, 0.7719], device='cuda:0')
data: tensor([[6.5575e+02, 6.0376e+02, 9.4230e+02, 1.3836e+03, 8.5206e-01, 0.0000e+00],
        [1.8564e+03, 8.9438e+01, 2.2949e+03, 7.9067e+02, 7.8061e-01, 0.0000e+00],
        [1.4979e+03, 9.1147e+01, 2.9410e+03, 1.2961e+03, 7.7191e-01, 7.0000e+00]], device='cuda:0')
id: None
is_track: False
orig_shape: (1728, 3072)
shape: torch.Size([3, 6])
xywh: tensor([[ 799.0215,  993.6780,  286.5478,  779.8459],
        [2075.6628,  440.0538,  438.5531,  701.2318],
        [2219.4639,  693.6486, 1443.1260, 1205.0026]], device='cuda:0')
xywhn: tensor([[0.2601, 0.5750, 0.0933, 0.4513],
        [0.6757, 0.2547, 0.1428, 0.4058],
        [0.7225, 0.4014, 0.4698, 0.6973]], device='cud

In [5]:
#print(results)
print(type(results[0]))
print(dir(results[0]))
print(type(results[0].boxes))

<class 'ultralytics.engine.results.Results'>
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__len__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_apply', '_keys', 'boxes', 'cpu', 'cuda', 'keypoints', 'masks', 'names', 'new', 'numpy', 'obb', 'orig_img', 'orig_shape', 'path', 'plot', 'probs', 'save', 'save_crop', 'save_dir', 'save_txt', 'show', 'speed', 'summary', 'to', 'tojson', 'update', 'verbose']
<class 'ultralytics.engine.results.Boxes'>


In [4]:
print(results[0].probs)

None


In [6]:
print(results[0].boxes)

ultralytics.engine.results.Boxes object with attributes:

cls: tensor([0., 0., 7.], device='cuda:0')
conf: tensor([0.8521, 0.7806, 0.7719], device='cuda:0')
data: tensor([[6.5575e+02, 6.0376e+02, 9.4230e+02, 1.3836e+03, 8.5206e-01, 0.0000e+00],
        [1.8564e+03, 8.9438e+01, 2.2949e+03, 7.9067e+02, 7.8061e-01, 0.0000e+00],
        [1.4979e+03, 9.1147e+01, 2.9410e+03, 1.2961e+03, 7.7191e-01, 7.0000e+00]], device='cuda:0')
id: None
is_track: False
orig_shape: (1728, 3072)
shape: torch.Size([3, 6])
xywh: tensor([[ 799.0215,  993.6780,  286.5478,  779.8459],
        [2075.6628,  440.0538,  438.5531,  701.2318],
        [2219.4639,  693.6486, 1443.1260, 1205.0026]], device='cuda:0')
xywhn: tensor([[0.2601, 0.5750, 0.0933, 0.4513],
        [0.6757, 0.2547, 0.1428, 0.4058],
        [0.7225, 0.4014, 0.4698, 0.6973]], device='cuda:0')
xyxy: tensor([[ 655.7476,  603.7550,  942.2953, 1383.6010],
        [1856.3864,   89.4379, 2294.9395,  790.6697],
        [1497.9009,   91.1474, 2941.0269, 1296

In [9]:
print(results[0].boxes.xyxy)
print(results[0].boxes.conf)
print(results[0].boxes.cls)

tensor([[ 655.7476,  603.7550,  942.2953, 1383.6010],
        [1856.3864,   89.4379, 2294.9395,  790.6697],
        [1497.9009,   91.1474, 2941.0269, 1296.1499]], device='cuda:0')
tensor([0.8521, 0.7806, 0.7719], device='cuda:0')
tensor([0., 0., 7.], device='cuda:0')


In [14]:
class_names = model.names
print(class_names)
icnt = 0
for each_class_name in results[0].boxes.cls:
  print(f'This object was found in the image: {class_names[int(each_class_name)]}  Here is the conf: {results[0].boxes.conf[icnt]} ')
  icnt = icnt + 1

{0: 'person', 1: 'bicycle', 2: 'car', 3: 'motorcycle', 4: 'airplane', 5: 'bus', 6: 'train', 7: 'truck', 8: 'boat', 9: 'traffic light', 10: 'fire hydrant', 11: 'stop sign', 12: 'parking meter', 13: 'bench', 14: 'bird', 15: 'cat', 16: 'dog', 17: 'horse', 18: 'sheep', 19: 'cow', 20: 'elephant', 21: 'bear', 22: 'zebra', 23: 'giraffe', 24: 'backpack', 25: 'umbrella', 26: 'handbag', 27: 'tie', 28: 'suitcase', 29: 'frisbee', 30: 'skis', 31: 'snowboard', 32: 'sports ball', 33: 'kite', 34: 'baseball bat', 35: 'baseball glove', 36: 'skateboard', 37: 'surfboard', 38: 'tennis racket', 39: 'bottle', 40: 'wine glass', 41: 'cup', 42: 'fork', 43: 'knife', 44: 'spoon', 45: 'bowl', 46: 'banana', 47: 'apple', 48: 'sandwich', 49: 'orange', 50: 'broccoli', 51: 'carrot', 52: 'hot dog', 53: 'pizza', 54: 'donut', 55: 'cake', 56: 'chair', 57: 'couch', 58: 'potted plant', 59: 'bed', 60: 'dining table', 61: 'toilet', 62: 'tv', 63: 'laptop', 64: 'mouse', 65: 'remote', 66: 'keyboard', 67: 'cell phone', 68: 'microw